networks:
  internal-net:
    external: true
    driver: bridge

services:
  api:
    image: api:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: template-api
    restart: always
    depends_on:
      - mongodb
      - cache
      - db
    ports:
      - 5678:5678
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - internal-net
    volumes:
      - .:/code

  mongodb:
    image: mongo:5.0.22
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - internal-net

  celery-beat:
    image: api:latest
    container_name: celery_beat
    restart: always
    command: ["celery", "--app", "src.utils.celery", "beat", "-l", "debug"]
    depends_on: [cache]
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - ./.env
    networks:
      - internal-net

  celery-worker:
    image: api:latest
    container_name: celery_worker
    restart: always
    command:
      [
        "celery",
        "--app",
        "src.utils.celery",
        "worker",
        "--concurrency=4",
        "-l",
        "info",
      ]
    depends_on: [cache]
    env_file:
      - ./.env
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - internal-net

  cache:
    image: redis:6.2-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: "redis-server --save 20 1 --requirepass redispass --loglevel warning"
    volumes:
      - cache:/data
    networks:
      - internal-net

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: admin
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgresspass
    volumes:
      - pgdata:/var/lib/postgresql/dat
    networks:
      - internal-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - internal-net

volumes:
  pgdata:
  cache:
    driver: local
  mongodb:
