#!/bin/bash

echo "Stating Application!"

if [ "$1" == 'debug' ];then
    sudo docker-compose build --no-cache && sudo docker-compose up
    exit 1
fi

if [ "$1" == 'only-run' ];then
    sudo docker-compose build --no-cache && sudo docker-compose up -d
    exit 1
fi


if [ "$1" == 'tests' ];then
    pytest --cov=. ./src/tests/
fi
